version: "3.2"
services:
  db:
    image: zaubermaerchen/mariadb-mroonga
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: bpuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bpdb
    volumes:
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /home